export const hovedplan = {
  sheet: "ARK 01",
  title: "Markedskart, hovedplan",
  scale: "NTS",
  rev: "A",
  owner: "FLO BRANNSIKRING",
  market: "Hva har skjedd hos kunden?",
  rule: {
    stamp: "FLO-regelen",
    when: "Når noe endres, blir påpekt eller er uklart:",
    action: "Kontakt FLO tidlig",
    before: "Før tiltak settes i gang og prisen kommer",
  },
  caseAsk: "Hva gjelder saken?",
  cases: [
    {
      id: "tilsyn",
      label: "Tilsyn / avvik",
      href: "/situasjon/papekt",
      notes: [
        "Fått avvik",
        "Fått pålegg",
        "Fått tilsyn",
        "Foreslått tiltak",
        "Usikker på krav",
        "Uenighet om løsning",
      ],
    },
    {
      id: "prosjekt",
      label: "Bygg / prosjekt",
      href: "/situasjon/endres",
      notes: [
        "Nybygg",
        "Ombygging",
        "Rehabilitering",
        "Bruksendring",
        "Prosjektering",
        "Eksisterende bygg",
      ],
    },
    {
      id: "drift",
      label: "Eiendom / drift",
      href: "/situasjon/uklart",
      notes: [
        "Overtatt bygg",
        "Flere bygg",
        "Gammel dokumentasjon",
        "Ny leietaker",
        "Internkontroll",
        "Endret drift",
      ],
    },
  ],
  solveAsk: "Hvordan løses saken?",
  solve: [
    { id: "fag", label: "Riktig FLO-fag", href: "/losninger" },
    { id: "leveranse", label: "Konkret leveranse", href: "/kontakt" },
    { id: "oppfolging", label: "Oppfølging", href: "/kontakt" },
  ],
  whoAsk: "Deretter: hvem det gjelder",
  claimAsk: "Påstand eller krav?",
  claimFlow: [
    "Det kunden har hørt / tror",
    "Påstand",
    "FLO fagvurdering",
    "Lovdata / DSB / DiBK / fagkilder",
    "Krav / anbefaling / må vurderes",
    "Hva betyr det for kunden?",
    "Hva bør de gjøre?",
    "FLO",
  ],
  goalAsk: "Kunden finner FLO fordi",
  goals: [
    { label: "Vi har fått et avvik", href: "/situasjon/papekt" },
    { label: "Vi skal bygge om", href: "/situasjon/endres" },
    { label: "Hva gjelder?", href: "/situasjon/uklart" },
    { label: "Er dette faktisk et krav?", href: "/fag-og-kunnskap/pastand-eller-krav" },
    { label: "Har vi kontroll?", href: "/hvem-er-du/virksomhet-bruker" },
    { label: "Kan vi gjøre dette selv?", href: "/fag-og-kunnskap/hva-kan-avklares-digitalt" },
    { label: "Når bør brannfaget inn?", href: "/losninger/ribr" },
  ],
} as const;
