export const roles = [
  { id: "owner", label: "Eier", asks: "Hva gjelder for dette bygget, og kan vi dokumentere det?" },
  { id: "user", label: "Bruker / virksomhet", asks: "Bruker vi bygget innenfor forutsetningene, og kan vi vise det?" },
  { id: "tenant", label: "Leietaker", asks: "Hva er mitt ansvar, og hva eier må holde?" },
  { id: "manager", label: "Forvalter / facility", asks: "Har vi oversikt per bygg, ikke bare per perm?" },
  { id: "client", label: "Byggherre", asks: "Hvilke premisser må være avklart før plan og anbud?" },
  { id: "architect", label: "Arkitekt", asks: "Hva må avklares før planløsningen tegnes ferdig?" },
  { id: "ribr", label: "RIBr / prosjekterende brann", asks: "Konsept, detalj eller kontroll, hvilken jobb er dette?" },
  { id: "applicant", label: "Ansvarlig søker", asks: "Hva må være avklart før søknad?" },
  { id: "contractor", label: "Entreprenør", asks: "Er tiltaket et krav, eller et prosjektvalg?" },
  { id: "controller", label: "Uavhengig kontrollerende", asks: "Holder underlaget for det som skal bygges?" },
  { id: "authority", label: "Tilsynsmyndighet", asks: "Hva er observert, og mot hvilket grunnlag?" },
  { id: "private", label: "Privat / bolig", asks: "Hva må avklares før kjeller, loft eller utleiedel tas i bruk?" },
] as const;

export const buildingStates = [
  "NEW_BUILD",
  "EXISTING_BUILDING",
  "REHABILITATION",
  "CHANGE_OF_USE",
  "TENANT_CHANGE",
  "EXTENSION",
  "REBUILD",
  "NEW_EQUIPMENT",
  "CHANGED_OPERATION",
  "DOCUMENTATION_MISSING",
  "AS_BUILT_MISMATCH",
  "DEVIATION_FOUND",
  "ORDER_RECEIVED",
  "HANDOVER",
  "NORMAL_OPERATION",
] as const;

export const changeTypes = [
  { id: "use", label: "Bruk" },
  { id: "occupancy", label: "Personbelastning" },
  { id: "layout", label: "Planløsning" },
  { id: "tenant", label: "Leietaker" },
  { id: "escape", label: "Rømning" },
  { id: "fireLoad", label: "Brannenergi / lagring" },
  { id: "equipment", label: "Utstyr / prosess" },
  { id: "organisation", label: "Organisasjon / ansvar" },
  { id: "installation", label: "Installasjon" },
  { id: "documentation", label: "Dokumentasjon" },
] as const;

export const documents = [
  { id: "FIRE_STRATEGY", label: "Brannsikkerhetsstrategi" },
  { id: "FIRE_CONCEPT", label: "Brannkonsept" },
  { id: "FIRE_DRAWINGS", label: "Branntegninger" },
  { id: "DETAIL_DESIGN", label: "Detaljprosjektering" },
  { id: "AS_BUILT", label: "As built / FDV" },
  { id: "CONTROL_REPORT", label: "Kontrollrapport" },
  { id: "DEVIATION", label: "Avvik" },
  { id: "INSPECTION", label: "Tilsyn / pålegg" },
  { id: "RISK", label: "Risikovurdering" },
  { id: "INTERNAL_CONTROL", label: "Internkontroll" },
  { id: "EVACUATION_PLAN", label: "Evakueringsplan" },
  { id: "TRAINING", label: "Opplæring / øvelse" },
] as const;

export const lifecycle = [
  { id: "idea", label: "Idé / tidligfase" },
  { id: "premises", label: "Brannpremisser" },
  { id: "concept", label: "Brannkonsept" },
  { id: "detail", label: "Detaljprosjektering" },
  { id: "procurement", label: "Anbud" },
  { id: "execution", label: "Utførelse" },
  { id: "control", label: "Kontroll" },
  { id: "handover", label: "Overtakelse" },
  { id: "operation", label: "Drift" },
  { id: "change", label: "Endring" },
  { id: "inspection", label: "Tilsyn" },
  { id: "deviation", label: "Avvik" },
  { id: "correction", label: "Utbedring" },
] as const;

export const domains = [
  { id: "ansvar", label: "Ansvar", href: "/fag-og-kunnskap/eier-eller-bruker" },
  { id: "krav", label: "Krav", href: "/fag-og-kunnskap/pastand-eller-krav" },
  { id: "risiko", label: "Risiko", href: "/fag-og-kunnskap/hva-har-endret-seg" },
  { id: "bygg-bruk", label: "Bygg og bruk", href: "/fag-og-kunnskap/hva-har-endret-seg" },
  { id: "dokumentasjon", label: "Dokumentasjon", href: "/fag-og-kunnskap/stemmer-dokumentasjonen" },
  { id: "ribr", label: "Brannkonsept / RIBr", href: "/losninger/ribr" },
  { id: "detalj", label: "Detaljprosjektering", href: "/fag-og-kunnskap/brannkonsept-eller-prosjektering" },
  { id: "kontroll", label: "Kontroll", href: "/losninger/brannteknisk-utforelse" },
  { id: "avvik", label: "Avvik / pålegg", href: "/fag-og-kunnskap/vi-har-fatt-avvik" },
  { id: "bruksendring", label: "Bruksendring", href: "/fag-og-kunnskap/nar-bruken-endres" },
  { id: "eksisterende", label: "Eksisterende bygg", href: "/fag-og-kunnskap/gammel-dokumentasjon" },
  { id: "internkontroll", label: "Internkontroll", href: "/losninger/brannvernradgivning" },
  { id: "opplaring", label: "Opplæring", href: "/losninger/brannvernradgivning" },
  { id: "beredskap", label: "Øvelser / beredskap", href: "/losninger/brannvernradgivning" },
  { id: "kartlegging", label: "3D-skanning / kartlegging", href: "/fag-og-kunnskap/3d-skanning" },
  { id: "utforelse", label: "Utførelse / utbedring", href: "/losninger/brannteknisk-utforelse" },
  { id: "overtakelse", label: "Overtakelse", href: "/fag-og-kunnskap/overtakelse" },
  { id: "drift", label: "Drift / vedlikehold", href: "/losninger/brannvernradgivning" },
  { id: "eier-bruker", label: "Eier / bruker", href: "/fag-og-kunnskap/eier-eller-bruker" },
  { id: "digitalt", label: "Digitalt / hybrid / fysisk", href: "/fag-og-kunnskap/hva-kan-avklares-digitalt" },
  { id: "endring", label: "Endring", href: "/fag-og-kunnskap/hva-har-endret-seg" },
  { id: "privat", label: "Privat / bolig", href: "/hvem-er-du/privat" },
] as const;

export const algorithm = [
  { id: "who", ask: "Hvem har ansvaret?" },
  { id: "situation", ask: "Har dere fått avvik, eller skal dere bygge om?" },
  { id: "change", ask: "Har bruken endret seg?" },
  { id: "building", ask: "Hva slags bygg er dette?" },
  { id: "use", ask: "Hvordan brukes det i dag?" },
  { id: "responsibility", ask: "Eier eller leietaker?" },
  { id: "risk", ask: "Hva er risikoen?" },
  { id: "documentation", ask: "Stemmer papirene?" },
  { id: "requirement", ask: "Er dette et krav?" },
  { id: "alternatives", ask: "Finnes andre løsninger?" },
  { id: "next", ask: "Hva gjør vi nå?" },
] as const;

export const decisionGraphs = [
  {
    id: "tenant-change",
    label: "Ny leietaker",
    steps: [
      "Endret bruk?",
      "Endret persontall?",
      "Endret brannenergi?",
      "Endret rømning?",
      "Stemmer konseptet?",
      "Må noe prosjekteres?",
      "Må noe utføres?",
      "Hva skal dokumenteres?",
      "Hvem har ansvaret i drift?",
    ],
    href: "/fag-og-kunnskap/hva-har-endret-seg",
  },
  {
    id: "claim",
    label: "Påstand eller krav",
    steps: ["Påstand", "Fakta", "Kilde", "Klassifisering", "Alternativer", "Beslutning"],
    href: "/fag-og-kunnskap/pastand-eller-krav",
  },
  {
    id: "mismatch",
    label: "Dokumentasjon mot bygg",
    steps: ["Hva er dokumentert", "Hva står i bygget", "Hva er endret", "Hva mangler", "Digitalt eller befaring", "Oppdatert spor"],
    href: "/fag-og-kunnskap/stemmer-dokumentasjonen",
  },
  {
    id: "utleiedel",
    label: "Utleiedel i bolig",
    steps: [
      "Situasjon",
      "Bygg",
      "Bruk",
      "Hva skal endres",
      "Dokumentasjon",
      "Faktisk krav",
      "Mulige løsninger",
      "Digital vurdering / befaring",
      "Hva gjør vi nå?",
    ],
    href: "/fag-og-kunnskap/utleiedel",
  },
] as const;
